version: '3.4'

services:
  db:
    image: postgres:10
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - '.env'
    ports:
      - '5432:5432'
  core:
    env_file:
      - '.env'
    build:
      context: .
      target: 'development'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    command: ['yarn', 'start:dev']
    depends_on:
      - db
    ports:
      - '8100:3000'

volumes:
  db_data:
    driver: local
